import React from 'react';
import './styles/Entrevista.css';
import Ghostcoreapple from './Ghostcoreapple.jsx'

const EntrevistaOnum = () => {

    return (
        <>
        <Ghostcoreapple />
        <div className='interviewContent'>
            <h1 className='interviewTitle'>Entrevista a Pedro Castillo de Onum</h1>
            <h2 className='interviewSubtitle'>El pasado sábado 9 de marzo pasamos el día en la RootedCON, una conferencia de ciberseguridad que este año ha reunido a más de 6000 personas. Gracias al evento tuvimos la suerte de conocer a Pedro Castillo, fundador de <a className='enlaceIVW' href='https://onum.com'>Onum</a>, una empresa dueña de la única plataforma de observabilidad de datos agnóstica. A continuación os dejamos con unas cuestiones que le planteamos a Pedro.</h2>
            <h2 className='interviewDate'>2024-03-20 - Álvaro García Pizarro</h2>
            <hr className='lineaInterview'></hr>
            <h3 className='interviewQuestion'>👉🏻 En pocas palabras ¿Qué es ONUM? Porque de primeras es un producto complejo y completo pero una vez te paras a analizarlo ves el potencial que tiene.</h3>
            <p className='interviewAnswer'>Como la única plataforma de observabilidad de datos verdaderamente agnóstica, Onum observa y agrega valor a los datos en tránsito para ofrecer alertas en tiempo real puro sobre anomalías, posibles riesgos de seguridad y problemas del sistema. Se integra perfectamente con la infraestructura de IT existente para obtener información profunda de cualquier tipo de datos, desde cualquier fuente. Onum también ayuda a optimizar los costos de tu plataforma de análisis de datos al reducir los datos, evitar la dependencia de proveedores y alinear el valor de cada conjunto de datos con las acciones específicas tomadas. Para maximizar la eficiencia, el mercado de Onum proporciona flujos de datos compartidos, herramientas comunitarias y módulos de valor agregado para potenciar casos de uso adicionales a medida que las necesidades crecen.</p>
            <h3 className='interviewQuestion'>👉🏻 ¿Por qué aparece Onum?</h3>
            <p className='interviewAnswer'>En los últimos años, los datos han crecido en tamaño y diversidad, volviéndose cada vez más inmanejables. Como resultado, los administradores de TI y seguridad son incapaces de aislar sus datos valiosos del ruido, lo que dificulta, y a veces hace imposible, utilizar datos accionables para sus decisiones críticas para el negocio.
<br></br><br></br>Onum resuelve este problema al adoptar una visión holística de los datos en tránsito para simplificar las tareas de los líderes de TI y brindar seguridad para obtener las profundas ideas que necesitan para tomar decisiones rápidas en cualquier cantidad de casos de uso, en tiempo real puro. Entre otras características, estas son las que hacen a Onum únicos:
<ol>
<li> Tiempo real: recopila y observa datos lo más cerca posible de donde se generan para alertar a los líderes de TI y seguridad en tiempo real sobre cualquier anormalidad, riesgo de seguridad potencial o problemas del sistema a medida que los datos atraviesan la red.</li>
<li> Agnóstico: se centra exclusivamente en la observabilidad de datos y, por lo tanto, es la única plataforma de orquestación verdaderamente agnóstica en el mercado que permite a los clientes maximizar su inversión en su infraestructura existente.</li>
<li> Extensible: el Marketplace de Onum amplía las capacidades listas para usar de la plataforma al proporcionar acceso a flujos de datos compartidos, herramientas comunitarias y módulos de valor añadido.</li>
</ol></p>
            <h3 className='interviewQuestion'>👉🏻 Cada vez más empresas utilizan el cloud (aws, azure, google…) pero hay muchas que utilizan una infraestructura híbrida, ¿Cómo hacen Onum para recolectar todos los datos de ambos extremos?</h3>
            <p className='interviewAnswer'>Onum está diseñado para recopilar datos eficientemente desde cualquier fuente donde se generen, en todos los aspectos de la red híbrida, incluidos los activos físicos locales, los que se encuentran en múltiples nubes públicas y privadas, y los dispositivos IoT en diversas ubicaciones y capas de la red. Todos los datos se agregan y se observan, luego se reducen, enriquecen, normalizan y optimizan antes de enrutarlos a cualquier destino.
            <br></br><br></br>Los Listeners, que reciben los datos, se colocan lo más cerca posible de donde se generan, en cualquier ubicación de la red híbrida (nube, local, IoT) para recopilar todos los datos pertinentes en el mismo momento en que se generan. Luego, los oyentes envían esos datos a otros componentes basados en el borde de la arquitectura de Onum para ser observados, enriquecidos y optimizados. Los metadatos se envían simultáneamente a la Nube de Onum, para que todos los datos, de todas las fuentes, puedan ser observados juntos en tiempo real, para una comprensión completa del contexto.</p>
            <h3 className='interviewQuestion'>👉🏻 Nos encontramos en la RootedCon y muchos de los oyentes están interesados en cómo se implementa la ciberseguridad en una plataforma de esta magnitud. Al final dependiendo del cliente tratareis datos de tarjetas bancarias, datos biométricos… ¿Cómo se gestiona todo esto internamente?</h3>
            <p className='interviewAnswer'>La ciberseguridad se implementa en la Plataforma Onum de varias formas.  En primer lugar, para garantizar la privacidad de los datos en tránsito, la plataforma proporciona mecanismos para cifrar las comunicaciones con los más altos estándares de seguridad TLS, incluso permitiendo la autenticación de ambas partes con TLS Mutuo. La plataforma también puede configurarse para que los datos que se procesan en tiempo real nunca se almacenen o, si es necesario activar las cachés de eventos, éstas se ubiquen en discos cifrados con las máximas garantías. 
            <br></br><br></br>Además, algunos clientes tienen conjuntos de datos que incluyen información altamente sensible, como números de tarjetas de crédito o informes de salud, que nunca deben enviarse fuera de su entorno. Asimismo, estos datos pueden ser necesarios para más de un caso de uso e incluso almacenarse en múltiples plataformas de análisis. La plataforma Onum resuelve este desafío al permitirles aplicar reglas a los flujos, observando y enmascarando u ofuscando estos datos en tiempo real. Independientemente del caso de uso y del número de plataformas de análisis involucradas, cualquier dato sensible puede transformarse inmediatamente para llegar a su destino. 
            <br></br><br></br>Por otro lado, también reforzamos la seguridad en nuestra plataforma, por lo que se audita continuamente a nivel de software e infraestructura bajo el lema "La seguridad no es un producto, es un proceso".</p>
            <h3 className='interviewQuestion'>👉🏻 Tenéis varios casos de uso como: data reduction, data management, data exfiltration pero el que más nos ha llamado la atención es el de real-time data enrichment en el que hacéis enriquecimiento de datos y tenéis un ejemplo en la web muy interesante de cómo lo utilizáis para detectar un ataque, no sé si nos puedes explicar un poco más en profundidad cómo lo hacéis?</h3>
            <p className='interviewAnswer'>Como comenta el caso de uso al que haces referencia, la plataforma Onum se enfrenta a este desafío permitiendo utilizar flujos (Pipelines) listos para usar o desarrollar flujos de trabajo para detectar estos eventos en tiempo real. Una vez que se identifica un evento, consultará automáticamente a un repositorio de datos para extraer información adicional sobre el usuario conectado.
Esta información adicional, se agregará al evento antes de enviarlo a la plataforma de análisis. Dependiendo de la información que se extraiga, el evento también puede enviarse a una aplicación interna para activar una alerta. Internamente, la correlación de los datos se realiza mediante los denominados “Lookups”, datos creados en la plataforma por los clientes o proporcionados por Onum. Pueden incluir CMDBs, GEOIP, Private GEOIP, IOCs o Lookups personalizados.
<br></br><br></br>Cada evento que es recibido por Onum puede ser parseado para identificar en él distintos campos, como usuarios, direcciones IP, dominios, etc. Estos campos sirven como claves para enriquecer el evento con los “lookups” disponibles. Toda esta operativa se realiza en tiempo real, sobre cada evento, de manera que dichos eventos salen hacia las plataformas destino con una información más detallada y valiosa. Además, este enriquecimiento también facilita que los datos se puedan filtrar del ruido, separando los eventos que realmente aportan valor de los que no.
Por poner un ejemplo más concreto, Onum recopila Indicadores de Compromiso (IOC) publicados en distintas fuentes para que los clientes puedan enriquecer sus eventos con esta información y aumentar sus niveles de inteligencia, reduciendo así su tiempo de respuesta a los ataques.</p>
            <hr className='lineaInterview'></hr>
            <h2 className='interviewFinal'>Agradecer a Pedro su tiempo por responder nuestras cuestiones y recomendaros pasar por su web <a className='enlaceIVW' href='https://onum.com'>onum.com</a> para descubrir en profundidad su propuesta de valor.</h2>
        </div>
        </>
    );
};

export default EntrevistaOnum;