name: Deploy Infrastructure and App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-south-2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Format Terraform
      run: terraform fmt -check

    - name: Plan Terraform
      run: |
        pwd
        cd infrastructure
        terraform plan

    - name: Apply Terraform
      run: terraform apply -auto-approve

    - name: Build React app
      run: |
        pwd
        cd CommandShow-Website
        npm install
        npm run build:vite

    - name: Deploy React app to S3
      run: |
        aws s3 sync build/ s3://my-react-app